### PR TITLE
Add symlinks for .so files

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@isuruf it would be super appreciated if this gets in.

The removal of the symlinks breaks xtensor's binders and I am giving a webinar on xtensor tomorrow!

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@SylvainCorlay, ping me once tests pass

**Comment by SylvainCorlay** [comment]
Thanks @isuruf. Tests are passing!

**Comment by SylvainCorlay** [comment]
Thanks, this works perfectly now!

**Pull request merged**
