### PR TITLE
Revert #38 (Move symlinks back into libblas)

### PR DESCRIPTION
**Pull request by isuruf**
cc @minrk, @SylvainCorlay 

Adds a `blas-devel` package as suggested by @minrk and restoring symlinks in libblas for now.

### CODE REVIEW

**Comment by minrk** [comment]
Awesome, thanks! One question: there appears to be no netlib blas-devel, which means:

```
conda create -n blas blas-devel libblas=*=netlib
```

fails. This means that any package with a runtime dependency on blas-devel (e.g. fenics or petsc) will result in downstream packages either failing to install, or building with openblas.

I assume the correct fix is to either add netlib outputs for blas and blas-devel, either to this repo (probably best, to keep things in sync), or update lapack-feedstock to generate blas-devel.

**Comment by isuruf** [comment]
@minrk, can you send a PR to `lapack-feedstock`?

**Comment by isuruf** [comment]
@minrk ping.

**Comment by minrk** [comment]
opened: https://github.com/conda-forge/lapack-feedstock/pull/30

**Pull request merged**
