### PR TITLE
use libopenblas and add license

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/conda-forge/blas-feedstock/pull/4 and #31

### CODE REVIEW

**Comment by isuruf** [comment]
windows failures look like conda-build errors

**Comment by ocefpaf** [comment]
> windows failures look like conda-build errors

@msarahan do you mind taking a quick look and, if you agree it is a conda-build issue, I can open it upstream.

**Comment by ocefpaf** [comment]
@isuruf I was able to build these locally on my Windows machine. So it may be a conda-build bug but not an easily reproducible one :-/

I'm thinking about merging this and uploading the packages I built locally if my AppVeyor re-start fails the same way. Are you OK with that?

**Comment by ocefpaf** [comment]
Pasting the error here to make it easier:

```
Fixing permissions
Packaged license file.
INFO:conda_package_handling.tarball:Moving temporary package from C:\Users\appveyor\AppData\Local\Temp\1\tmp1ap4ithe\blas-2.11-mkl.tar.bz2 to C:\Users\appveyor\AppData\Local\Temp\1\tmpcwki1_zm\blas-2.11-mkl.tar.bz2 had some issues.  Error message was: PermissionError(13, 'Access is denied')
WARNING:conda.gateways.disk.delete:Could not remove or rename C:\Users\appveyor\AppData\Local\Temp\1\tmpcwki1_zm\blas-2.11-mkl.tar.bz2.  Please remove this file manually (you may need to reboot to free file handles)
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 2299, in build_tree
    notest=notest,
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 1596, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 984, in bundle_conda
    basename + ext, out_folder=tmp)
  File "C:\Miniconda36-x64\lib\site-packages\conda_package_handling\api.py", line 56, in create
    out = SUPPORTED_EXTENSIONS[ext].create(prefix, file_list, out_fn, out_folder, **kw)
  File "C:\Miniconda36-x64\lib\site-packages\conda_package_handling\tarball.py", line 112, in create
    "message was: {}".format(out_file, final_path, repr(e)))
  File "C:\Miniconda36-x64\lib\tempfile.py", line 807, in __exit__
    self.cleanup()
  File "C:\Miniconda36-x64\lib\tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Miniconda36-x64\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Miniconda36-x64\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Miniconda36-x64\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp1ap4ithe\\blas-2.11-mkl.tar.bz2'
```

**Comment by ocefpaf** [comment]
Closing and opening to toggle Azure.

**Comment by ocefpaf** [comment]
Using an older `conda-build` solves it.

**Comment by ocefpaf** [comment]
Great, now `osx osx_blas_implopenblasblas_impl_liblibopenblas.0.dylib` is failing :-(


```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2299, in build_tree
    notest=notest,
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1596, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 971, in bundle_conda
    output['checksums'] = create_info_files(metadata, files, prefix=metadata.config.host_prefix)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 677, in create_info_files
    checksums = create_info_files_json_v1(m, m.config.info_dir, prefix, files, files_with_prefix)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 773, in create_info_files_json_v1
    files_json_files = build_info_files_json_v1(m, prefix, files, files_with_prefix)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 753, in build_info_files_json_v1
    "size_in_bytes": os.path.getsize(path),
  File "/usr/local/miniconda/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/miniconda/conda-bld/blas-split_1559343412384/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libblas.3.dylib'
##[error]Bash exited with code '1'.
```

**Comment by isuruf** [comment]
`libopenblas: 0.3.6-hdc02c5d_0 defaults` is the issue

**Comment by ocefpaf** [comment]
> `libopenblas: 0.3.6-hdc02c5d_0 defaults` is the issue

Yep. Updated 8 hours ago in https://github.com/AnacondaRecipes/openblas-feedstock/commit/7189b50d1563bd90ebdae306e54c160c613afbf2

I guess that it is time for `strict` :smile:

**Comment by isuruf** [comment]
https://github.com/AnacondaRecipes/openblas-feedstock/pull/3

**Comment by ocefpaf** [comment]
> [AnacondaRecipes/openblas-feedstock#3](https://github.com/AnacondaRecipes/openblas-feedstock/pull/3)


While that PR is good and will help us I'd rather our ecosystem was the trusted source of packages for what we build, relying on `defaults` only for what we do not build. Otherwise we'll have to keep working around issue like this and both channel will be slow to evolve.

**Comment by isuruf** [comment]
@ocefpaf, one issue is that then all users will have to use strict for this package to work correctly.

**Comment by ocefpaf** [comment]
> @ocefpaf, one issue is that then all users will have to use strict for this package to work correctly.

Or you mean they will stop opening issue daily about package incompatibilities :stuck_out_tongue_winking_eye: 

Conda-forge already recommends `strict` and I close all issue about mixing channels immediately by pointing people to the docs. The current situation is not better, that is not a reason to not do it.

**Comment by isuruf** [comment]
> Conda-forge already recommends strict and I close all issue about mixing channels immediately by pointing people to the docs. The current situation is not better, that is not a reason to not do it.

It's not a mixing channel issue. I don't use strict yet, but have conda-forge higher in priority. For some reason, conda solver installs defaults packages

**Comment by ocefpaf** [comment]
> It's not a mixing channel issue. I don't use strict yet, but have conda-forge higher in priority. For some reason, conda solver installs defaults packages

It is the name we are using for that kind of problem for a while. The more libraries and more dependencies in them you use the worse it gets b/c the solver does not guarantee channel priority, only `strict` solves that. @msarahan had a nice talk/slides at AnacondaCon about it. Not sure if there is a video, I'll try to find and send it to you.

**Comment by ocefpaf** [comment]
We have two serious issues here: one with conda-build, where I had to downgrade it to get this passing, and another one with `strict` channel to avoid `libopenblas` from `defaults` to be selected.

**Comment by ocefpaf** [comment]
I don't have a macOS to test why we cannot install `clang_osx-64=4` with `strict`.

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - clang_osx-64=4
```

We probably are vendorizing an old version of some of its dependency.

**Pull request merged**
