### PR TITLE
OpenBLAS 0.3.26 & MKL 2024.0; drop MKL on osx

### PR DESCRIPTION
**Pull request by h-vetinari**
Pick up recent releases. No news from the side of blis.

### CODE REVIEW

**Comment by h-vetinari** [comment]
PTAL @conda-forge/blas

**Comment by h-vetinari** [comment]
Gentle ping @conda-forge/blas; planning to merge on the weekend if there are no comments.

**Comment by larsoner** [comment]
If you update to the latest SciPy build on conda-forge (following https://github.com/conda-forge/scipy-feedstock/pull/268) or downgrade to OpenBLAS 0.3.25 you should be okay I think

**Comment by joshua-cogliati-inl** [comment]
> If you update to the latest SciPy build on conda-forge (following [conda-forge/scipy-feedstock#268](https://github.com/conda-forge/scipy-feedstock/pull/268)) or downgrade to OpenBLAS 0.3.25 you should be okay I think

Thanks.  Scipy 1.12 does solve this.

**Comment by h-vetinari** [comment]
With the merge of https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/642, this should now also be fixed for 1.11 and before

**Comment by jakirkham** [comment]
> No news from the side of blis.

Asked in issue ( https://github.com/flame/blis/issues/792 ). Sounds like they are still working out some kinks before doing a release

**Comment by jakirkham** [comment]
Looks like a new BLIS release should be coming out soon

**Pull request merged**
