### PR TITLE
Added symlinks to .pc files.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moorepants** [comment]
I'm not really sure exactly what I need to do to fix #58. I've copied the lines that were deleted from the openblas feedstock, but I assume this has got to be incorrect. I suspect that I need to somehow create symlinks to the netlib provided pc files? Not really sure.

**Comment by h-vetinari** [comment]
Have a look how the [lapack-feedstock](https://github.com/conda-forge/lapack-feedstock/blob/master/recipe/meta.yaml) does it (which builds the `netlib`-variants of all the packages here). I saw some `.pc` things there under `files:` per output. Might have to check the build scripts as well what is being done there, but should be a good starting point.

**Comment by moorepants** [comment]
Thanks for the tip, but I was under the impression that all .pc files from blas, cblas, lapack, and lapacke were no longer being provided from any of these feedstocks. This is what I see in my root conda env:

```
moorepants@agni:~$ conda list | grep blas
libblas                   3.9.0                5_openblas    conda-forge
libcblas                  3.9.0                5_openblas    conda-forge
liblapack                 3.9.0                5_openblas    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
moorepants@agni:~$ conda list | grep lapack
liblapack                 3.9.0                5_openblas    conda-for
moorepants@agni:~$ ls miniconda/lib/pkgconfig/lapack.*
ls: cannot access 'miniconda/lib/pkgconfig/lapack.*': No such file or directory
moorepants@agni:~$ ls miniconda/lib/pkgconfig/blas.pc
ls: cannot access 'miniconda/lib/pkgconfig/blas.pc': No such file or directory
moorepants@agni:~$ ls miniconda/lib/pkgconfig/cblas.pc
ls: cannot access 'miniconda/lib/pkgconfig/cblas.pc': No such file or directory
```

**Comment by moorepants** [comment]
I see this check:

https://github.com/conda-forge/lapack-feedstock/blob/master/recipe/meta.yaml#L73

but I'm not seeing that these files are installed on the user's end.

**Comment by moorepants** [comment]
I also opened this issue https://github.com/conda-forge/lapack-feedstock/issues/45 on the lapack feedstock, fyi.

**Comment by h-vetinari** [comment]
@moorepants 
You will only see what's being checked on the lapack feedstock by installing `conda install "libblas=*=*netlib"` (though it should ideally work the same with `conda install "blas=*=netlib"`).

To reiterate:
`{libblas, libcblas, liblapack, liblapacke, blas}-{ver}-{build_num}_netlib` are built in the lapack-feestock
`{libblas, libcblas, liblapack, liblapacke, blas}-{ver}-{build_num}_{blis, mkl, openblas}` are built in the blas-feestock (here)

My point was that whatever is being done to include them on the lapack-feedstock should very likely show you the way how to do it here as well.

**Comment by moorepants** [comment]
That helps clarify things for me. So, if I install the netlib versions I should see the pc files. I'll dig around in the lapack feedstock to see if I can find what actually creates the files.

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
It seems to me that in lapack-feedstock the pc files are created when cmake and make install are run. The files are then listed in the `files:` section of each output. I tried to do the same thing here, but the files do not seem to be present when the test runs. I'm not sure what is different. I also don't know what @isuruf recommended symlinks. I don't know what needs to be symlinked. Are the `.pc` files already present somewhere and symlinks are all that's needed. If so, where are the files located? They aren't in the `lib/pkgconfig` directory.

**Comment by moorepants** [comment]
This works:

```
moorepants@nandi:cyipopt(master)$ conda create -n lapackpctest lapack "libblas=*=*netlib"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/moorepants/miniconda/envs/lapackpctest

  added / updated specs:
    - lapack
    - libblas[build=*netlib]


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            1_gnu          22 KB  conda-forge
    lapack-3.9.0               |           netlib          11 KB  conda-forge
    libblas-3.9.0              |3_h92ddd45_netlib         201 KB  conda-forge
    libgfortran-ng-9.3.0       |      he4bcb1c_17          22 KB  conda-forge
    liblapack-3.9.0            |3_h92ddd45_netlib         3.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.2 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  lapack             conda-forge/linux-64::lapack-3.9.0-netlib
  libblas            conda-forge/linux-64::libblas-3.9.0-3_h92ddd45_netlib
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h5dbcf3e_17
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-9.3.0-he4bcb1c_17
  libgfortran5       conda-forge/linux-64::libgfortran5-9.3.0-he4bcb1c_17
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h5dbcf3e_17
  liblapack          conda-forge/linux-64::liblapack-3.9.0-3_h92ddd45_netlib



Downloading and Extracting Packages
_openmp_mutex-4.5    | 22 KB     | ############################################################################################################################################################################################################################################### | 100% 
_libgcc_mutex-0.1    | 3 KB      | ############################################################################################################################################################################################################################################### | 100% 
libblas-3.9.0        | 201 KB    | ############################################################################################################################################################################################################################################### | 100% 
liblapack-3.9.0      | 3.0 MB    | ############################################################################################################################################################################################################################################### | 100% 
lapack-3.9.0         | 11 KB     | ############################################################################################################################################################################################################################################### | 100% 
libgfortran-ng-9.3.0 | 22 KB     | ############################################################################################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate lapackpctest
#
# To deactivate an active environment, use
#
#     $ conda deactivate

moorepants@nandi:cyipopt(master)$ act lapackpctest 
(lapackpctest) moorepants@nandi:cyipopt(master)$ ls ~/miniconda/envs/lapackpctest/lib/pkgconfig/
blas.pc  lapack.pc
```

**Comment by moorepants** [comment]
This doesn't:
```
(lapackpctest) moorepants@nandi:cyipopt(master)$ conda install "libblas=*=*openblas"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/moorepants/miniconda/envs/lapackpctest

  added / updated specs:
    - libblas[build=*openblas]


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.9.0              |       6_openblas          11 KB  conda-forge
    liblapack-3.9.0            |       6_openblas          11 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          23 KB

The following NEW packages will be INSTALLED:

  libopenblas        conda-forge/linux-64::libopenblas-0.3.12-pthreads_h4812303_1

The following packages will be UPDATED:

  libblas                           3.9.0-3_h92ddd45_netlib --> 3.9.0-6_openblas
  liblapack                         3.9.0-3_h92ddd45_netlib --> 3.9.0-6_openblas



Downloading and Extracting Packages
libblas-3.9.0        | 11 KB     | ############################################################################################################################################################################################################################################### | 100% 
liblapack-3.9.0      | 11 KB     | ############################################################################################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(lapackpctest) moorepants@nandi:cyipopt(master)$ ls ~/miniconda/envs/lapackpctest/lib/pkgconfig/
ls: cannot access '/home/moorepants/miniconda/envs/lapackpctest/lib/pkgconfig/': No such file or directory
```

**Pull request closed without merging**
