### PR TITLE
Rebuild.

### PR DESCRIPTION
**Pull request by hmaarrfk**
I think the builds for ppc64le are kinda weird. it is resolving 

    libblas:            3.8.0-7_openblas      conda-forge

and not a newer build. I'm going to try to rerender this.

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Are the manual pinnings here on purpose?

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
@ocefpaf why are these errors showing up in the solver?

aarch
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 757, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 473, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
    force_remove, force_reinstall)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 145, in solve_for_diff
    force_remove)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 510, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs))
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 1054, in solve
    self.find_conflicts(specs)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 316, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - openblas=0.3.6 -> libopenblas==0.3.6=h6e990d7_3
Use "conda search <package> --info" to see the dependencies for each package.

```

linux
```
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'blas==2.11=openblas'}

```

**Comment by h-vetinari** [comment]
After more then 1.5 years, I think it's fair to close this one. In case there are other issues, please let us know!

**Pull request closed without merging**
