### PR TITLE
Move symlinks from libblas to blas

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by SylvainCorlay** [comment]
@isuruf the move of the symlinks appears to have broken our usecase with xtensor-blas incling.

**Comment by isuruf** [comment]
See https://github.com/conda-forge/blas-feedstock/issues/29#issuecomment-516612725

**Comment by SylvainCorlay** [comment]
I am a bit surprised by the back-and-forth here.

- initially the symlinks were in openblas and were removed. We had to update the binder to depend on `blas * openblas` to get the symlinks.
- now the symlinks are removed from blas?

**Comment by isuruf** [comment]
The symlinks are there in `blas`.

**Comment by SylvainCorlay** [comment]
It does not seem so.

**Comment by isuruf** [comment]
For eg: https://anaconda.org/conda-forge/blas/2.13/download/linux-64/blas-2.13-openblas.tar.bz2 has the symlinks.

**Comment by SylvainCorlay** [comment]
Sorry I was looking at libblas * openblas.

**Comment by isuruf** [comment]
Ah, okay. My reasons are at https://github.com/conda-forge/blas-feedstock/issues/29#issuecomment-496763409 . I asked for comments from May 28, and since there were none, I finally decided to do this. Let me know if there's anything I can do to help mitigate this issue.

**Comment by SylvainCorlay** [comment]
We could mitigate on our side by requiring `blas * openblas` instread of `libblas * openblas`.

**Pull request merged**
