### PR TITLE
migrator redux

### PR DESCRIPTION
**Pull request by hmaarrfk**
closes #17

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@mariusvniekerk @jjhelmus i touched up this recipe for the migration.
Seems to be passing, but this is a strange package, so if one of you could have a look that would be great!

**Comment by mariusvniekerk** [comment]
you need to use the BLAS_VARIANT somewhere in the meta.yaml.  Right now its not being rendered in

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
Also we probably need to exclude mkl for platforms that don't have mkl

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
Thanks @mariusvniekerk

**Pull request merged**
